export const MOCK_LISTINGS = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    title: 'شقة طلابية مفروشة',
    location: 'حي الجامعة، الرياض',
    price: 1200,
    rating: 4.8,
    reviewCount: 24,
    ownerName: 'طارق جاويش',
    verifiedOwner: true,
    featured: true,
    favorite: false,
    available: true,
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1de2d93688?auto=format&fit=crop&q=80&w=800',
    title: 'غرفة خاصة بحمام مشترك',
    location: 'حي الملز، الرياض',
    price: 800,
    rating: 4.5,
    reviewCount: 12,
    ownerName: 'أحمد صالح',
    verifiedOwner: false,
    featured: false,
    favorite: true,
    available: true,
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
    title: 'استديو حديث للطلاب',
    location: 'حي النفل، الرياض',
    price: 1500,
    rating: 4.9,
    reviewCount: 56,
    ownerName: 'شركة مساكن',
    verifiedOwner: true,
    featured: true,
    favorite: false,
    available: true,
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
    title: 'سرير في غرفة مشتركة',
    location: 'حي الصحافة، الرياض',
    price: 500,
    rating: 4.2,
    reviewCount: 8,
    ownerName: 'محمد عبدالله',
    verifiedOwner: true,
    featured: false,
    favorite: false,
    available: false,
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800',
    title: 'شقة فاخرة قريب من المترو',
    location: 'حي الملقا، الرياض',
    price: 2200,
    rating: 5.0,
    reviewCount: 104,
    ownerName: 'سكنكم العقارية',
    verifiedOwner: true,
    featured: true,
    favorite: true,
    available: true,
  }
];
